# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Firezip.Firezip
PackageVersion: 1.0.0
InstallerType: inno
Scope: machine
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
UpgradeBehavior: install
FileExtensions:
  - zip
  - 7z
  - rar
  - tar
  - gz
  - bz2
ProductCode: '{8B036367-AE8C-4D88-B1F3-E18F2E23A534}_is1'
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/drodrigues55/firezip/releases/download/v1.0.0/FirezipSetup-x64-v1.0.0.exe
    InstallerSha256: A743F48366434899406F0CB22925EC9BFA2CA5697490CA27707EB67D7E9BCE0C
ManifestType: installer
ManifestVersion: 1.9.0
