<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Firezip.Core\Firezip.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.50.4" />
    <PackageReference Include="SharpSevenZip" Version="2.0.128" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
